import { type RouteConfig, index, route, layout } from "@react-router/dev/routes";

export default [
  index("routes/_index.tsx"),
  route("history", "routes/history.tsx"),
  route("bookmarks", "routes/bookmarks.tsx"),
  route("api/interact", "routes/api.interact.ts"),
  route("api/comments", "routes/api.comments.ts"),
  route("api/search", "routes/api.search.ts"),
  route("api/ads/track", "routes/api.ads.track.ts"),
  route("api/ads/serve", "routes/api.ads.serve.ts"),
  route("search", "routes/search.tsx"),
  route("search-ai", "routes/search-ai.tsx"),
  route("recommended", "routes/recommended.tsx"),
  route("advertise", "routes/advertise.tsx"),
  route("advertise/checkout/:id", "routes/advertise.checkout.$id.tsx"),
  route("advertise/success", "routes/advertise.success.tsx"),
  route("video/:slug", "routes/video.$slug.tsx"),
  route("category/:slug", "routes/category.$slug.tsx"),
  route("login", "routes/login.tsx"),
  route("register", "routes/register.tsx"),
  route("logout", "routes/logout.tsx"),
  route("privacy", "routes/privacy.tsx"),
  route("terms", "routes/terms.tsx"),
  route("dmca", "routes/dmca.tsx"),
  route("contact", "routes/contact.tsx"),
  route("faq", "routes/faq.tsx"),
  route("api/verify-age", "routes/api.verify-age.ts"),
  route("api/chat", "routes/api.chat.ts"),
  route("api/cron", "routes/api.cron.ts"),
  route("api/events", "routes/api.events.ts"),
  route("api/ip", "routes/api.ip.ts"),
  route("api/moderate", "routes/api.moderate.ts"),
  route("api/recommendations", "routes/api.recommendations.ts"),
  route("api/search-ai", "routes/api.search-ai.ts"),
  route("api/search-referrer", "routes/api.search-referrer.ts"),
  route("api/push-subscribe", "routes/api.push-subscribe.ts"),
  route("api/report", "routes/api.report.ts"),
  route("api/select-thumbnail", "routes/api.select-thumbnail.ts"),
  route("api/suggest-summary", "routes/api.suggest-summary.ts"),
  route("api/suggest-tags", "routes/api.suggest-tags.ts"),
  route("chat", "routes/chat.tsx"),
  route("share-target", "routes/share-target.tsx"),
  route("sitemap.xml", "routes/sitemap.xml.ts"),
  route("robots.txt", "routes/robots.txt.ts"),

  // Admin Routes
  route("admin", "routes/admin.tsx", [
    index("routes/admin._index.tsx"),
    route("analytics", "routes/admin.analytics.tsx"),
    route("videos", "routes/admin/videos/index.tsx"),
    route("videos/new", "routes/admin/videos/new.tsx"),
    route("videos/:id/edit", "routes/admin/videos/$id.edit.tsx"),
    route("tags", "routes/admin.tags.tsx"),
    route("categories", "routes/admin.categories.tsx"),
    route("comments", "routes/admin.comments.tsx"),
    route("ads", "routes/admin.ads.tsx"),
    route("ads/purchases", "routes/admin.ads.purchases.tsx"),
    route("revenue", "routes/admin.revenue.tsx"),
    route("moderations", "routes/admin.moderations.tsx"),
    route("block-status", "routes/admin.block-status.tsx"),
    route("notifications", "routes/admin.notifications.tsx"),
  ]),
] satisfies RouteConfig;
